### ISSUE TITLE
Greater eye caused the ender eye cannot be used on End Portal Frame

### ISSUE THREAD

**Issue by Cio18** [kwpugh/greater_eye_forge#1]
When I use this mod, the ender eye cannot be used on End Portal Frame.
So I cannot use the ender eye to activate the End Portal Frame.
Ho do I fix it?

**Comment by kwpugh** [comment]
This mod does nothing to the vanilla ender eye.  The Greater Eyes of Ender cannot be used in the same way in the end portal.

**Comment by kwpugh** [comment]
I tested this and the vanilla eye of ender works fines in end portal frame while Greater Eye mod is loaded.
